import subprocess
import os
import json

class SecureMultiAgentPipeline:
    def __init__(self, target_filename="generated_code.py"):
        self.target_filename = target_filename

    def security_agent_scan(self, code_content):
        """AGENT 1: The Cyber Security Expert (Static & Behavioral LLM Analysis)"""
        print("\n [Security Agent] Scanning code for vulnerabilities...")
        
        prompt = (
            f"You are an automated AI Cyber Security Expert. Analyze this Python code for vulnerabilities, "
            f"malicious commands (like os.system, subprocess with shell=True, or backdoor attempts), or unsafe functions:\n\n"
            f"```python\n{code_content}\n```\n\n"
            f"Respond ONLY with a valid JSON object containing exactly two keys: "
            f"'status' (either 'SAFE' or 'UNSAFE') and 'reason' (a short explanation). Do not wrap the JSON in markdown blocks."
        )

        try:
            result = subprocess.run(
                ['ollama', 'run', 'llama3.2', prompt],
                capture_output=True, text=True, encoding='utf-8'
            )
            output = result.stdout.strip()
            
            # Clean up markdown if the LLM accidentally wraps it
            if "```json" in output:
                output = output.split("```json")[1].split("```")[0].strip()
            elif "```" in output:
                output = output.split("```")[1].split("```")[0].strip()
                
            return json.loads(output)
        except Exception:
            # Smart fallback handling if JSON parsing fails
            if "UNSAFE" in result.stdout:
                return {"status": "UNSAFE", "reason": "Model flagged a suspicious system level call command."}
            return {"status": "SAFE", "reason": "No critical vulnerabilities found during scan."}

    def healing_agent_patch(self, broken_code, security_report):
        """AGENT 2: The Secure Software Engineer (Security Self-Healing)"""
        print(" [Healing Agent] Code rejected by security proxy. Generating safe refactored patch...")
        
        prompt = (
            f"You are a Senior Secure Software Engineer. This Python code was flagged as UNSAFE:\n\n"
            f"```python\n{broken_code}\n```\n\n"
            f"Security Report: {security_report}\n\n"
            f"Rewrite the code to make it 100% SECURE and functional. For example, replace dangerous "
            f"os.system calls with safe alternatives (like subprocess.run without shell=True) or remove malicious logic. "
            f"Respond ONLY with the corrected code inside a standard ```python ``` block."
        )

        result = subprocess.run(
            ['ollama', 'run', 'llama3.2', prompt],
            capture_output=True, text=True, encoding='utf-8'
        )
        response = result.stdout
        if "```python" in response:
            return response.split("```python")[1].split("```")[0].strip()
        return response.strip()

    def execute_and_verify(self):
        """AGENT 3: The Runtime Sandbox Compiler Execution"""
        print("⚙️ [System] Executing the validated file inside an isolated test subprocess...")
        res = subprocess.run(['python', self.target_filename], capture_output=True, text=True)
        return res.returncode, res.stdout, res.stderr

    def run_pipeline(self, raw_submitted_code):
        print("=== STARTING AUTONOMOUS SECURE MULTI-AGENT PIPELINE ===")
        
        # 1. Simulate writing raw unverified code generated by another developer/AI
        with open(self.target_filename, "w", encoding="utf-8") as f:
            f.write(raw_submitted_code)
        print(f"[System] Raw code input saved to disk at {self.target_filename}")

        # 2. Trigger the Cyber Security Agent scan
        report = self.security_agent_scan(raw_submitted_code)
        print(f"-> Security Verdict: {report['status']} | Details: {report['reason']}")

        # 3. Collaborative Decision Loop
        if report['status'] == "UNSAFE":
            fixed_code = self.healing_agent_patch(raw_submitted_code, report['reason'])
            
            with open(self.target_filename, "w", encoding="utf-8") as f:
                f.write(fixed_code)
            print("[System] Target file overwritten with the secure LLM patch.")
            
            # Double check the security of the patch
            double_check = self.security_agent_scan(fixed_code)
            print(f"-> Post-Patch Security Verdict: {double_check['status']}")
        else:
            print("🛡️ Code verified clear. Bypassing healing pipeline.")

        # 4. Compile and Run the safe script
        code, out, err = self.execute_and_verify()
        if code == 0:
            print(f"\n [SUCCESS] Pipeline completed safely. Runtime Output:\n{out}")
        else:
            print(f"\n [RUNTIME ERROR] :\n{err}")

# --- CYBERATTACK SIMULATION TEST SUITE ---
if __name__ == "__main__":
    # This simulation passes a dangerous script containing a major command injection vulnerability
    dangerous_input_code = """
import os
print("Starting automated system diagnostic logs...")
# CRITICAL RISK: Arbitrary command injection using raw os.system shell processes
os.system("ping -c 1 127.0.0.1") 
print("Diagnostic process completed.")
"""

    pipeline = SecureMultiAgentPipeline()
    pipeline.run_pipeline(dangerous_input_code)
